web:
  image: catalasan/php7-xdebug
  ports:
    - "80:80"
    - "443:443"
  links:
    - mysql
  volumes:
    - .:/var/www/html
    - "./build/php.ini:/usr/local/etc/php/php.ini"
    - "./build/apache-vhost.conf:/etc/apache2/sites-enabled/custom-vhost.conf"
    - "./build/certs:/etc/ssl/private"
  env_file:
      - build/env

mysql:
  image: mysql:5.6.23
  ports:
      - "3306:3306"
  # Add a persistent drive to have the mysql DB locally and not only in the container
  volumes:
      - ./build/mysql/data:/var/lib/mysql
  env_file:
    - build/env
